newgorkha/newgorkha/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
  
    # path("tinymce/", include("tinymce.urls")),
    
]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
admin.site.site_header = "ecommerce Administration"
admin.site.site_title = "ecommerce Admin Portal"
admin.site.index_title = "Welcome to ecommerce Admin Portal"

newgorkha/web/urls.py
from django.urls import path,include
from . import views

app_name = "user"

urlpatterns = [
    path("about-us", views.about_us, name="about_us"),
    path("blog-detail", views.blog_detail, name="blog_detail"),
    path("blog-grid", views.blog_grid, name="blog_grid"),
    path("blog-list", views.blog_list, name="blog_list"),
    path("cart/<int:id>", views.addtocart, name="addtocart"),
    path("cart", views.viewcart, name="viewcart"),
    path("checkout", views.checkout, name="checkout"),
    path("coming-soon", views.coming_soon, name="coming_soon"),
    path("compare", views.compare, name="compare"),
    path("contact-us", views.contact_us, name="contact_us"),
    path("faq", views.faq, name="faq"),
    path("forgot", views.forget_password, name="forgot password"),
    path('change password/<token>/', views.change_password, name="change password"),
    path("delete/<int:id>", views.deletefromwishlist, name="deletefromwishlist"),
    path("deletecart/<int:id>", views.deletefromcart, name="deletefromcart"),
    path("index-2", views.index_2, name="index_2"),
    path("index-3", views.index_3, name="index_3"),
    path("index-4", views.index_4, name="index_4"),
    path("index-5", views.index_5, name="index_5"),
    path("index-6", views.index_6, name="index_6"),
    path("index-7", views.index_7, name="index_7"),
    path("index-8", views.index_8, name="index_8"),
    path("index-9", views.index_9, name="index_9"),
    path("", views.index, name="index"),
    path("login", views.login_views, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("order-success", views.order_success, name="order_success"),
    path("order-tracking", views.order_tracking, name="order_tracking"),
    path("otp", views.otp, name="otp"),
    path("product-4-image", views.product_4_image, name="product_4_image"),
    path("product-bottom-thumbnail", views.product_bottom_thumbnail, name="product_bottom_thumbnail"),
    path("product-bundle", views.product_bundle, name="product_bundle"),
    path("product-left-thumbnail", views.product_left_thumbnail, name="product_left_thumbnail"),
    path("product-right-thumbnail", views.product_right_thumbnail, name="product_right_thumbnail"),
    path("product/<int:id>", views.product, name="product"),
    path("product-sticky", views.product_sticky, name="product_sticky"),
    path("search", views.search, name="search"),
    path("seller-become", views.seller_become, name="seller_become"),
    path("seller-dashboard", views.seller_dashboard, name="seller_dashboard"),
    path("seller-detail-2", views.seller_detail_2, name="seller_detail_2"),
    path("seller-detail", views.seller_detail, name="seller_detail"),
    path("seller-grid-2", views.seller_grid_2, name="seller_grid_2"),
    path("seller-grid", views.seller_grid, name="seller_grid"),
    path("shop-banner", views.shop_banner, name="shop_banner"),
    path("shop-category-slider", views.shop_category_slider, name="shop_category_slider"),
    path("shop-category/<int:id>", views.shop_category, name="shop_category"),
    path("shop/<int:id>", views.shop, name="shop"),
    path("shop-list", views.shop_list, name="shop_list"),
    path("shop-right-sidebar", views.shop_right_sidebar, name="shop_right_sidebar"),
    path("shop-top-filter", views.shop_top_filter, name="shop_top_filter"),
    path("sign-up", views.user_register, name="sign_up"),
    path("dashboard", views.user_dashboard, name="dashboard"),
    path("wishlist/<int:id>", views.addtowishlist, name="addtowishlist"),
    path("wishlist",views.viewwishlist,name="viewwishlist"),
    path("404", views.error_404, name="error_404"),
    path("whatsapp",views.whatsappFun, name="whatsapp"),
    # cart add ajax
    path("addquantity/",views.addQuantity, name="addquantity"),
    path("lessquantity/",views.lessQuantity,name="lessquantity")
]

newgorkha/templates/web/partials/footer.html
{% load static %}

<footer class="section-t-space">
    <div class="container-fluid-lg">
        <div class="service-section">
            <div class="row g-3">
                <div class="col-12">
                    <div class="service-contain">
                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/product.svg' %} "
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Every Fresh Products</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/delivery.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Free Delivery For Order Over $50</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/discount.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Daily Mega Discounts</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/market.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Best Price On The Market</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="main-footer section-b-space section-t-space">
            <div class="row g-md-4 g-3">
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-logo">
                        <div class="theme-logo">
                            <a href="/">
                                <img src="{% static 'web/images_new/New Gorkha Logo/New Gorkha Logo/New Gorkha Logo1.png' %}"
                                    class="blur-up lazyload" alt="">
                            </a>
                        </div>

                        <div class="footer-logo-contain">
                            <p>We are a friendly bar serving a variety of cocktails, wines and beers. Our bar is a
                                perfect place for a couple.</p>

                            <ul class="address">
                                <li>
                                    <i data-feather="home"></i>
                                    <a href="javascript:void(0)">Kondotty malapuram , Near calicut Airport</a>
                                </li>
                                <li>
                                    <i data-feather="mail"></i>
                                    <a href="javascript:void(0)">support@https://gedexo.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                </div>

                <div class="col-xl col-lg-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Useful Links</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="/" class="text-content">Home</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-xl-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Help Center</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="{% url 'user:search' %}" class="text-content">Search</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-title">
                        <h4>Contact Us</h4>
                    </div>

                    <div class="footer-contact">
                        <ul>
                            <li>
                                <div class="footer-number">
                                    <i data-feather="phone"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Hotline 24/7 :</h6>
                                        <h5>+91 888 104 2340</h5>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <div class="footer-number">
                                    <i data-feather="mail"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Email Address :</h6>
                                        <h5>gedexohr@gmail.com</h5>
                                    </div>
                                </div>
                            </li>

                            {% comment %} <li class="social-app mb-0">
                                <h5 class="mb-2 text-content">Download App :</h5>
                                <ul>
                                    <li class="mb-0">
                                        <a href="https://play.google.com/store/apps" target="_blank">
                                            <img src="{% static 'web/images/playstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                    <li class="mb-0">
                                        <a href="https://www.apple.com/in/app-store/" target="_blank">
                                            <img src="{% static 'web/images/appstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                </ul>
                            </li> {% endcomment %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        
    </div>
</footer>

newgorkha/templates/web/partials/header.html
{% load static %}

<head>

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />


</head>


<header class="pb-md-4 pb-0">
    <div class="header-top">
        <div class="container-fluid-lg">
            <div class="row">
            </div>
        </div>
    </div>

    <div class="top-nav top-header sticky-header">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="navbar-top">
                        <!-- <button class="navbar-toggler d-xl-none d-inline navbar-menu-button" type="button"
                            data-bs-toggle="offcanvas" data-bs-target="#primaryMenu">
                            <span class="navbar-toggler-icon">
                                <i class="fa-solid fa-bars"></i>
                            </span>
                        </button> -->
                        <a href="/" class="web-logo nav-logo">
                            <img src="{% static 'web/images_new/New Gorkha Logo/New Gorkha Logo/New Gorkha Logo1.png' %}"
                                class="img-fluid blur-up lazyload" alt="">
                        </a>

                        <div class="middle-box">
                           

                            {% comment %} instead of location all categories {% endcomment %}
                            <div class="header-nav">
                                <div class="header-nav-left">
                                <button class="dropdown-category">
                                    <i data-feather="align-left"></i>
                                    <span>All Categories</span>
                                </button>
        
                                <div class="category-dropdown">
                                    <div class="category-title">
                                        <h5>Categories</h5>
                                        <button type="button" class="btn p-0 close-button text-content">
                                            <span class="material-icons-outlined">
                                                close
                                                </span>
                                        </button>
                                    </div>
        
                                    <ul class="category-list food-menu-filter">
                                       {% for category in categories %}
                                        <li class="onhover-category-list">
                                            <a href="{{category.get_absolute_url}}" class="category-name">
                                                <img src="{{category.image.url}}" alt="">
                                                <h6>{{category.category}}</h6>
                                                <i class="fa-solid fa-angle-right"></i>
                                            </a>         
                                            <div class="onhover-category-box w-100 product-items">
                                                <div class="list-1">
                                                    
                                                    <ul>
                                                        {% for subcategory in category.get_subcategories %}

                                                        <li>
                                                            <a href="{% url 'web:shop_category' subcategory.id %}">{{subcategory.subcategory }}</a>
                                                        </li>

                                                        {% endfor %}    
                                                    </ul>
                                                    
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                            {% comment %} end  all categories {% endcomment %}

                            <div class="search-box">
                                <form method="GET" action="{% url 'web:search' %}">
                                <div class="input-group">
                                    
                                        <input type="text" class="form-control" placeholder="I'm searching for..."
                                        aria-label="Recipient's username" aria-describedby="button-addon2" name="search"required>
                                        <button class="btn" type="submit" id="button-addon2">
                                            <i data-feather="search"></i>
                                        </button>
                                    
                                </div>
                            </form>
                            </div>
                        </div>

                        <div class="rightside-box">
                            <div class="search-full">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i data-feather="search" class="font-light"></i>
                                    </span>
                                    <input type="text" class="form-control search-type" placeholder="Search here..">
                                    <span class="input-group-text close-search">
                                        <i data-feather="x" class="font-light"></i>
                                    </span>
                                </div>
                            </div>
                            <ul class="right-side-menu">
                                <li class="right-side">
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <div class="search-box">
                                                <i data-feather="search"></i>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <!-- <li class="right-side">
                                    <a href="{% url 'web:contact_us' %}" class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <i data-feather="phone-call"></i>
                                        </div>
                                        <div class="delivery-detail">
                                            <h6>24/7 Delivery</h6>
                                            <h5>+91 888 104 2340</h5>
                                        </div>
                                    </a>
                                </li> -->
                                <li class="right-side">
                                    <a href="{%url 'web:viewwishlist' %}" class="btn p-0 position-relative header-wishlist">
                                        <i data-feather="heart"></i>
                                    </a>
                                </li>
                                <li class="right-side">
                                    <a href="{%url 'web:viewcart' %}" class="btn p-0 position-relative header-wishlist">
                                        <i data-feather="shopping-cart"></i>
                                    </a>
                                </li>





                               
                                <li class="right-side onhover-dropdown">
                                    
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <i data-feather="user"></i>
                                        </div>
                                        <div class="delivery-detail">
                                            <h6>Hello,</h6>
                                            <h5>My Account</h5>
                                        </div>
                                    </div>
                                   
                                    <div class="onhover-div onhover-div-login">
                                         <ul class="user-box-name">
                                           
                                            {% if status == 1 %}
                                            <li class="product-box-contain">
                                                <i></i>
                                                <a href={% url 'web:sign_up' %}>New Account</a>
                                            </li>
                                            <li class="product-box-contain">
                                                <a href={% url 'web:logout' %}>logout</a>
                                            </li>
                                            {% else %}
                                            <li class="product-box-contain">
                                                <a href={% url 'web:login' %}>Log in</a>
                                            </li>
                                            <li class="product-box-contain">
                                                <a href={% url 'web:sign_up' %}>Register</a>
                                            </li>
                                            {% endif %}
                                        </ul> 
                                    </div>
                                   
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% comment %} phone categories {% endcomment %}
    <div class="container-fluid-lg">
        <div class="row">
            <div class="col-12">
                <div class="header-nav">
                   <div class="header-nav-left">
                        <div class="category-dropdown">
                            <div class="category-title">
                                <h5>Categories</h5>
                                <button type="button" class="btn p-0 close-button text-content">
                                    <i class="fa-solid fa-xmark"></i>
                                </button>
                            </div>

                            <ul class="category-list">
                                <li class="onhover-category-list">
                                    {% for category in categories %}
                                    <a href="{{category.get_absolute_url}}" class="category-name">
                                        <img src="{{category.image.url}}"
                                            alt="">
                                        <h6>{{category.category}}</h6>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </a>
                                    <div class="onhover-category-box">
                                        {% for subcategory in category.get_subcategories %}
                                            <div class="category-title-box">
                                                <a href="{% url 'web:shop_category' subcategory.id %}"><h5>{{subcategory.subcategory}}</h5></a>
                                            </div>
                                            <ul>
                                                <!-- {% for products in subcategory.get_products %}
                                                <li>
                                                    <a href="{% url 'web:product' products.id %}">{{products.product}}</a>
                                                </li>
                                                {% endfor %} -->
                                            </ul>
                                        {% endfor %}
                                    </div>
                                    {% endfor %}
                                </li>
                            </ul>
                        </div>
                    </div> 

                    <div class="header-nav-middle">
                        <div class="main-nav navbar navbar-expand-xl navbar-light navbar-sticky">
                            <div class="offcanvas offcanvas-collapse order-xl-2" id="primaryMenu">
                                <div class="offcanvas-header navbar-shadow">
                                    <h5>Menu</h5>
                                    <button class="btn-close lead" type="button" data-bs-dismiss="offcanvas"
                                        aria-label="Close"></button>
                                </div>
                          
                            </div>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</header>
{% block js %}

{% endblock %}